name: PHP Code Style

on: pull_request

permissions:
  contents: read

jobs:
  PHP-CS-Fixer:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        php-version:
          - "8.3"
          - "8.4"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
          extensions: "json, mbstring, mongodb, pdo"

      - name: Install PHP CS Fixer
        run: COMPOSER=.github/workflows/composer.php-cs-fixer.json composer install --no-interaction --no-progress

      - name: Run php-cs-fixer
        run: vendor/bin/php-cs-fixer fix --dry-run --config=./php_cs.php -v --using-cache=no --diff --quiet
