name: PHP Static Analysis

on: pull_request

jobs:
  Lint:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        php-version:
          - 8.3
          - 8.4
    steps:
      - name: Checkout repository
        uses: "actions/checkout@v4"

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
          extensions: "mbstring"

      - name: Install Composer dependencies
        run: composer install --no-progress --no-interaction

      - name: Check syntax (php-parallel-lint)
        run: vendor/bin/parallel-lint src tests

  PHPStan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - 8.3
          - 8.4
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
          extensions: "mbstring"

      - name: Install Composer dependencies
        run: composer install --no-progress --no-interaction

      - name: Run PHPStan analysis
        run: vendor/bin/phpstan analyze
